# Copyright (c) 2025 anonysec. All rights reserved.
# Proprietary and confidential. Unauthorized copying, distribution, or use is prohibited.

"""added uuid for users

Revision ID: 076bf2e03771
Revises: 494ff940dc52
Create Date: 2025-11-24 22:08:26.083044

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "076bf2e03771"
down_revision: str | None = "494ff940dc52"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    with op.batch_alter_table("users") as batch_op:
        batch_op.add_column(sa.Column("uuid", sa.String(), nullable=True))

    conn = op.get_bind()
    results = conn.execute(sa.text("SELECT id FROM users WHERE uuid IS NULL"))
    for row in results:
        user_id = row[0]
        import uuid

        new_uuid = str(uuid.uuid4())
        conn.execute(
            sa.text("UPDATE users SET uuid = :uuid WHERE id = :id"),
            {"uuid": new_uuid, "id": user_id},
        )

    with op.batch_alter_table("users") as batch_op:
        batch_op.create_unique_constraint("uq_users_uuid", ["uuid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "uuid")
    # ### end Alembic commands ###
