# Copyright (c) 2025 anonysec. All rights reserved.
# Proprietary and confidential. Unauthorized copying, distribution, or use is prohibited.

"""add last node usage for users table

Revision ID: 0f7118ad11ee
Revises: e5dbbcdc6ef1
Create Date: 2026-05-08 16:04:51.051171

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0f7118ad11ee"
down_revision: str | None = "e5dbbcdc6ef1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_settings_id", table_name="settings")
    op.drop_table("settings")
    op.add_column("users", sa.Column("last_node_usage", sa.BigInteger(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_node_usage")
    op.create_table(
        "settings",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("tunnel_address", sa.VARCHAR(), nullable=True),
        sa.Column("port", sa.INTEGER(), nullable=False),
        sa.Column("protocol", sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_settings_id", "settings", ["id"], unique=False)
    # ### end Alembic commands ###
