"""add total traffic

Revision ID: 2533cbca76ca
Revises: 076bf2e03771
Create Date: 2026-02-26 22:19:05.010105

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2533cbca76ca'
down_revision: str | None = '076bf2e03771'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total')
    # ### end Alembic commands ###
