# Copyright (c) 2025 anonysec. All rights reserved.
# Proprietary and confidential. Unauthorized copying, distribution, or use is prohibited.

"""update node table

Revision ID: 494ff940dc52
Revises: 9710b4923333
Create Date: 2025-10-02 00:01:29.641787

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "494ff940dc52"
down_revision: str | None = "9710b4923333"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("nodes", sa.Column("protocol", sa.String(), nullable=False))
    op.add_column("nodes", sa.Column("ovpn_port", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nodes", "ovpn_port")
    op.drop_column("nodes", "protocol")
    # ### end Alembic commands ###
