"""add used traffic

Revision ID: e5dbbcdc6ef1
Revises: 2533cbca76ca
Create Date: 2026-02-26 22:39:19.138838

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e5dbbcdc6ef1'
down_revision: str | None = '2533cbca76ca'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('used', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'used')
    # ### end Alembic commands ###
